name: smarthub

description: SmartHub website application

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.1.0
  fluro: ^2.0.5
  sprintf: ^7.0.0
  url_strategy: ^0.2.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  responsive_sizer: ^3.2.0
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.1
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_charts: ^23.1.40
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/translations/

  generate: true
  uses-material-design: true
